version: '3'

services:
    mongo:
        image: "mongo"
        restart: always
        networks:
            - collab-network
    
    server:
        depends_on:
            - mongo
                # condition: service_healthy
        # links:
        #     - "mongo"
        restart: always
        image: thedavekwon/collab_server
        # build: server
        ports:
            - 8080:8080
        #   - target: 8080
        #     x-aws-protocol: http
        environment:
            - CHOKIDAR_USEPOLLING=true
            - MONGO_ADDR=mongo
        networks:
            - collab-network
            
            
    client:
        depends_on: 
            - server
        # links:
        #     - "server"
        restart: always
        image: thedavekwon/collab_client
        # build: client
        ports:
            - 80:80
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_SERVER_ADDR=server
        networks:
            - collab-network
      
networks:
    collab-network:
        driver: bridge