version: '3'

services:
    mongo:
        image: "mongo"
        restart: always
        networks:
            - collab-network
    
    server:
        depends_on:
            - mongo
        restart: always
        image: jampherpo/collab_server
        # build: server
        ports:
           - target: 8080
             x-aws-protocol: http
        environment:
            - CHOKIDAR_USEPOLLING=true
            - MONGO_ADDR=mongo
        networks:
            - collab-network
            
            
    client:
        depends_on: 
            - server
        restart: always
        image: jampherpo/collab_client
        # build: client
        ports:
            - 80:80
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_SERVER_ADDR=server
            # - REACT_APP_USER_POOL_ID=!Ref UserPool 
            # - REACT_APP_CLIENT_ID=!Ref UserPoolClient
        networks:
            - collab-network
      
networks:
    collab-network:
        driver: bridge

