version: '3'

services:
    mongo:
        image: "mongo"
        restart: always
        ports:
            - 27017
        networks:
            - collab-network
    
    server:
        depends_on:
            - mongo
                # condition: service_healthy
        # links:
        #     - "mongo"
        restart: always
        image: thedavekwon/collab_server
        ports:
            - 8080:8080
        environment:
            - MONGO_ADDR=mongo
        networks:
            - collab-network
            
            
    client:
        depends_on: 
            - server
        # links:
        #     - "server"
        restart: always
        image: thedavekwon/collab_client
        ports:
            - 80:80
        environment:
            - SERVER_ADDR=server
        networks:
            - collab-network
      
networks:
    collab-network:
        driver: bridge